language: groovy
jdk:
- oraclejdk8
before_deploy:
- ./add_to_maven_repo.sh
deploy:
  provider: releases
  api_key:
    secure: dljyo+cpdZvA0mSMBEGt+b6Uli+dCT/XBwbG78hM7IK8YavPkl8svBdIT+DVulDnOLyGb/kZ3qZmV34Ty57tvuEAFdxXUWt4gJbtalGuebZ6qcMDH45GHbLg470sKIma2AoNbbEI+j+8LY3702v7Ojip/Um0BdKIIIzCxBFlX5xyi4XgcSAY7ub5IMfFKe1qpqpKs91+hs147OnOEqghiaVfEVc34gD8uWieFUQdGDVG4/OxA6S/3mam57/KaXWp4uRjJki0qV0kayYmAHkmtRVR58/I8RbG/OjuZImTtdugMAFjD25UUh7XFZo36Jaor+IUbdiWa5Os0vLltFgD/TGPrnn63gKDtG/GJVA+2bP6b7i3L8YjCEhQpVwatDXT9tGW2bhHEWVZ4D7V1qoxTGSsgAX9s5qFOgxd6rsUbf0AkIud/tMsmrcOPjxw3aOH+a89hUpOiAp+dty+PetISeGWB8qPmVsO+dN92QassCK0JtOYUPldoakg2QRmlZSBfL9nAbLR6eIoVYPmj/wH6Mwey5DwPekvKmPf0ePTzXSZmuc62ryRVG8RXNFTOcmUiVm6CcrhhuBaOA5hTkNpHhMJOsXB9wJ81aQ4ltnZPkLjD+kLVkOsMKw4M8Oskp+h3rIPuI1KD+qrqb6rmb/aLjlBvrWheql8tbNMXvD8fcA=
  file_glob: true
  file: build/libs/*.jar
  on:
    tags: true
    repo: delphyne/gradle-serviceloader-manifest
env:
  global:
    secure: lxRP9ynTHpp1ZY6zyYr9/JxHBcnTYU9kKHlz9pJV6BRbnjuOsLDP7KMtOpGHLpLVdj/wNi/Bqol6Dk8eKT30nk6LhR+Q5tgGBrBnQ/7SPEFgk74R7GGUq8cFeOfMAMbIUKVb6wvUSXmpISbV8IxJv6obDtM/2QXZhF7sz/OUdZh+GSkvUUA5iUMxYXVyVLnPlocLXXaoABf/GWyVe0m1NJYOSaybaraQ2saEAzBY8SrAHMdNts2GJDp7rMJ4DFvCHH/bn0GzeIETY7P0js57ZyVxozej6FDUAGks+coHE605UQAerJNGBxpvk60NO2ywrhqOozl8joBSkeRw7ZoEIcPzYjX8IsD8KFYUF6TKjhxzLMHNp47UQLGkUSOL9H1Hnjg03MvsspHVRYc9yonhw3zN/jp4/4JVBpP7DG+H3q6jAXaCdoVDpHVcoPpVXtEkVhnLAseVrP4fY3EFPAm2XHUZZ3kpFEBGm60M6i/n+kRdlE0UBR2PZQAMr/smll7EaLPg9WjkEHo8jvJPVG5X4PoCEFOdzLKcdPtw7t6tCZ+WukMSmrDUHihKe8eLjs29XI9Y6VRlUgJPAO8TVV5nOv/XdGZe2nhLTS1G7WwuBI5I1ZBaZNM9yxjtqNn/LzX4gbRbvsQ+dHZaNzVVu3wB6KbpFi9cEkriWvh+IgSD+CQ=
